<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Order;
use App\Models\Customer;
use App\Models\DiningTable;
use App\Models\Location;
use Carbon\Carbon;

class OrderSeeder extends Seeder
{
    public function run(): void
    {
        $customers = Customer::all();
        $tables = DiningTable::all();
        $locations = Location::all();
        
        $orderStatuses = ['pending', 'received', 'preparing', 'ready', 'completed', 'cancelled'];
        $orderTypes = ['dine-in', 'pickup', 'delivery'];
        
        // Generate orders for the last 30 days to next week
        $startDate = Carbon::now()->subDays(30);
        $endDate = Carbon::now()->addDays(7);
        
        // Load all telegram users for guest scenarios
        $telegramUsers = \App\Models\TelegramUser::all();

        for ($i = 0; $i < 200; $i++) {
            $location = $locations->random();
            $orderDate = $this->randomDateBetween($startDate, $endDate);
            
            // SCENARIO: Telegram Guest Order (10% chance)
            $isTelegramGuest = $telegramUsers->isNotEmpty() && rand(1, 100) <= 10;
            if ($isTelegramGuest) {
                $customer = null;
                $telegramUser = $telegramUsers->random();
                $orderType = ['pickup', 'delivery'][array_rand(['pickup', 'delivery'])]; // Guests usually pickup/delivery
            } else {
                $customer = $customers->random();
                $telegramUser = null;
                $orderType = $orderTypes[array_rand($orderTypes)];
            }

            // Get table for dine-in orders
            $table = null;
            if ($orderType === 'dine-in') {
                $locationTables = $tables->where('floor.location_id', $location->id);
                $table = $locationTables->isNotEmpty() ? $locationTables->random() : null;
            }
            
            $status = $this->getOrderStatus($orderDate);
            
            $subtotal = $this->generateSubtotal();
            $tax = $this->calculateTax($subtotal);
            $discount = $this->generateDiscount();
            $total = $this->calculateTotal($subtotal, $tax, $discount);
            
            // LINKING: Find or Create Reservation
            $reservationId = null;
            if ($table && $orderType === 'dine-in') {
                // Try to find existing
                $reservation = \App\Models\Reservation::where('table_id', $table->id)
                    ->where('reservation_date', $orderDate->format('Y-m-d'))
                    ->whereBetween('reservation_time', [
                        $orderDate->copy()->subHour()->format('H:i:s'),
                        $orderDate->copy()->addHour()->format('H:i:s')
                    ])
                    ->first();
                
                // If not found, create one with 50% probability to ensure some links exist
                if (!$reservation && rand(1, 100) <= 50) {
                     $reservation = \App\Models\Reservation::create([
                        'location_id' => $location->id,
                        'customer_id' => $customer?->id ?? \App\Models\Customer::first()->id, // Fallback to first customer
                        'table_id' => $table->id,
                        'code' => strtoupper(\Illuminate\Support\Str::random(8)),
                        'reservation_number' => 'RES-AUTO-' . rand(1000, 9999),
                        'reserved_for' => $customer?->name ?? 'Guest',
                        'party_size' => rand(2, 4),
                        'reservation_date' => $orderDate->format('Y-m-d'),
                        'reservation_time' => $orderDate->format('H:i:s'),
                        'status' => 'completed',
                        'special_requests' => null,
                        'notes' => 'Auto-generated by OrderSeeder',
                     ]);
                }

                $reservationId = $reservation?->id;
            }

            // LINKING: Find or Create Shift
            $shift = \App\Models\Shift::where('location_id', $location->id)
                ->where('date', $orderDate->format('Y-m-d'))
                ->where('start_time', '<=', $orderDate->format('H:i:s'))
                ->where('end_time', '>=', $orderDate->format('H:i:s'))
                ->inRandomOrder()
                ->first();
            
            // If no shift covering this time, find ANY shift on that day, or create one
            if (!$shift) {
                // Try any shift on that day
                $shift = \App\Models\Shift::where('location_id', $location->id)
                    ->where('date', $orderDate->format('Y-m-d'))
                    ->first();
                
                // If still no shift, create a fallback shift
                if (!$shift) {
                    $employee = \App\Models\Employee::whereHas('user', function($q) use($location) {
                        $q->where('default_location_id', $location->id);
                    })->inRandomOrder()->first() ?? \App\Models\Employee::first();

                    if ($employee) {
                        $shift = \App\Models\Shift::create([
                            'employee_id' => $employee->id,
                            'location_id' => $location->id,
                            'position_id' => $employee->position_id,
                            'date' => $orderDate->format('Y-m-d'),
                            'start_time' => '08:00:00',
                            'end_time' => '23:00:00', // Long shift to cover order
                            'shift_type' => 'morning',
                            'status' => 'completed',
                            'published_at' => now(),
                        ]);
                    }
                }
            }
            
            $shiftId = $shift?->id;
            $employeeId = $shift ? $shift->employee_id : ($shiftId ? null : \App\Models\Employee::inRandomOrder()->first()->id);

            $order = Order::create([
                'location_id' => $location->id,
                'customer_id' => $customer?->id,
                'telegram_user_id' => $telegramUser?->id ?? ($customer?->telegram_id ? \App\Models\TelegramUser::where('telegram_id', $customer->telegram_id)->first()?->id : null),
                'table_id' => $table?->id,
                'reservation_id' => $reservationId,
                'shift_id' => $shiftId,
                'employee_id' => $employeeId, // Assign to employee on shift if found
                'order_number' => $this->generateOrderNumber($location->code, $orderDate),
                'order_type' => $orderType,
                'status' => $status,
                'subtotal' => $subtotal,
                'tax_amount' => $tax,
                'discount_amount' => $discount,
                'total_amount' => $total,
                'special_instructions' => $this->getSpecialInstructions(),
                'estimated_ready_time' => $this->getEstimatedReadyTime($orderDate, $orderType),
                'ordered_at' => $orderDate,
                'completed_at' => $status === 'completed' ? $orderDate->copy()->addMinutes(rand(20, 60)) : null,
            ]);
        }
    }

    private function randomDateBetween(Carbon $start, Carbon $end): Carbon
    {
        $timestamp = rand($start->timestamp, $end->timestamp);
        return Carbon::createFromTimestamp($timestamp);
    }

    private function getOrderStatus(Carbon $orderDate): string
    {
        $now = Carbon::now();
        
        // Future orders
        if ($orderDate->isAfter($now)) {
            return ['pending', 'received'][array_rand(['pending', 'received'])];
        }
        
        $hoursAgo = $now->diffInHours($orderDate);
        
        if ($hoursAgo > 24) {
            return rand(0, 10) < 9 ? 'completed' : 'cancelled';
        } elseif ($hoursAgo > 2) {
            return ['completed', 'completed', 'completed', 'cancelled'][array_rand(['completed', 'completed', 'completed', 'cancelled'])];
        } else {
            return ['pending', 'received', 'preparing', 'ready', 'completed'][array_rand(['pending', 'received', 'preparing', 'ready', 'completed'])];
        }
    }

    private function generateOrderNumber(string $locationCode, Carbon $date): string
    {
        return $locationCode . '-' . $date->format('Ymd') . '-' . str_pad(rand(1, 9999), 4, '0', STR_PAD_LEFT) . '-' . substr(md5(microtime()), 0, 3);
    }

    private function generateSubtotal(): float
    {
        return round(rand(1500, 8000) / 100, 2); // $15.00 to $80.00
    }

    private function calculateTax(float $subtotal): float
    {
        return round($subtotal * 0.10, 2); // 10% tax
    }

    private function generateDiscount(): float
    {
        return rand(0, 100) < 20 ? round(rand(200, 1000) / 100, 2) : 0.00; // 20% chance of discount
    }

    private function calculateTotal(float $subtotal, float $tax, float $discount): float
    {
        return round($subtotal + $tax - $discount, 2);
    }

    private function getSpecialInstructions(): ?string
    {
        $instructions = [
            null, null, null, null, // 40% no instructions
            'No spicy please',
            'Extra vegetables',
            'Well done',
            'On the side',
            'No onions',
            'Extra sauce',
            'Less salt',
            'Gluten free preparation',
            'Vegetarian option',
            'Make it spicy',
        ];
        
        return $instructions[array_rand($instructions)];
    }

    private function getEstimatedReadyTime(Carbon $orderDate, string $orderType): ?Carbon
    {
        $minutes = match($orderType) {
            'dine_in' => rand(15, 30),
            'pickup' => rand(20, 35),
            'delivery' => rand(30, 50),
            default => rand(20, 30),
        };
        
        return $orderDate->copy()->addMinutes($minutes);
    }
}
