<?php

namespace Database\Seeders\Prod;

use Illuminate\Database\Seeder;
use App\Models\Supplier;

class SupplierSeeder extends Seeder
{
    public function run(): void
    {
        $suppliers = [
            [
                'name' => 'Phnom Penh Produce Co.',
                'code' => 'SUP-001',
                'contact_name' => 'Sokha Chen',
                'contact_phone' => '+855-12-345-678',
                'email' => 'orders@phnompenhproduce.com',
                'address' => '123 Norodom Blvd, Phnom Penh',
                'type' => 'produce',
                'payment_terms' => 'net_30',
                'notes' => 'Local fresh produce supplier - Primary vendor',
                'is_active' => true,
            ],
            [
                'name' => 'Mekong Seafood Supply',
                'code' => 'SUP-002',
                'contact_name' => 'Dara Meas',
                'contact_phone' => '+855-12-456-789',
                'email' => 'sales@mekongseafood.com',
                'address' => '456 Sisowath Quay, Phnom Penh',
                'type' => 'seafood',
                'payment_terms' => 'net_15',
                'notes' => 'Fresh seafood daily delivery - Excellent quality',
                'is_active' => true,
            ],
            [
                'name' => 'Kampot Spice Traders',
                'code' => 'SUP-003',
                'contact_name' => 'Kunthea Pich',
                'contact_phone' => '+855-12-567-890',
                'email' => 'info@kampotspices.com',
                'address' => '789 Street 13, Kampot',
                'type' => 'spices',
                'payment_terms' => 'net_30',
                'notes' => 'Premium Kampot pepper and spices - Award winning',
                'is_active' => true,
            ],
            [
                'name' => 'Asian Food Solutions',
                'code' => 'SUP-004',
                'contact_name' => 'Sovann Kim',
                'contact_phone' => '+855-12-678-901',
                'email' => 'orders@asianfoodsolutions.com',
                'address' => '101 Street 271, Phnom Penh',
                'type' => 'dry_goods',
                'payment_terms' => 'net_45',
                'notes' => 'Bulk dry goods supplier - Competitive pricing',
                'is_active' => true,
            ],
            [
                'name' => 'Battambang Rice Co.',
                'code' => 'SUP-005',
                'contact_name' => 'Chanthy Roth',
                'contact_phone' => '+855-12-789-012',
                'email' => 'sales@battambangrice.com',
                'address' => '202 National Road 5, Battambang',
                'type' => 'rice',
                'payment_terms' => 'net_30',
                'notes' => 'Premium jasmine rice supplier - Organic certified',
                'is_active' => true,
            ],
            [
                'name' => 'Siem Reap Organic Farms',
                'code' => 'SUP-006',
                'contact_name' => 'Bopha Prak',
                'contact_phone' => '+855-12-890-123',
                'email' => 'contact@srorganics.com',
                'address' => '303 Charles de Gaulle, Siem Reap',
                'type' => 'produce',
                'payment_terms' => 'net_15',
                'notes' => 'Organic vegetables and herbs - Premium quality',
                'is_active' => true,
            ],
            [
                'name' => 'Cambodia Beverage Co.',
                'code' => 'SUP-007',
                'contact_name' => 'Vibol Tep',
                'contact_phone' => '+855-12-901-234',
                'email' => 'orders@cambev.com',
                'address' => '404 Mao Tse Toung Blvd, Phnom Penh',
                'type' => 'beverages',
                'payment_terms' => 'net_30',
                'notes' => 'Beverages and drink supplies - Wide selection',
                'is_active' => true,
            ],
            [
                'name' => 'Kandal Poultry Farms',
                'code' => 'SUP-008',
                'contact_name' => 'Sophal Nget',
                'contact_phone' => '+855-12-012-345',
                'email' => 'orders@kandalpoultry.com',
                'address' => '505 National Road 4, Kandal',
                'type' => 'poultry',
                'payment_terms' => 'cod',
                'notes' => 'Fresh chicken and eggs - Daily deliveries',
                'is_active' => true,
            ],
            [
                'name' => 'Premium Meats Cambodia',
                'code' => 'SUP-009',
                'contact_name' => 'Ratanak Sok',
                'contact_phone' => '+855-12-123-456',
                'email' => 'sales@premiummeats.com.kh',
                'address' => '606 Russian Blvd, Phnom Penh',
                'type' => 'meat',
                'payment_terms' => 'net_15',
                'notes' => 'Premium beef, pork, and lamb - Import quality',
                'is_active' => true,
            ],
            [
                'name' => 'Golden Dairy Products',
                'code' => 'SUP-010',
                'contact_name' => 'Sreymom Chea',
                'contact_phone' => '+855-12-234-567',
                'email' => 'info@goldendairy.com.kh',
                'address' => '707 Monivong Blvd, Phnom Penh',
                'type' => 'dairy',
                'payment_terms' => 'net_30',
                'notes' => 'Dairy products and cheese - Temperature controlled',
                'is_active' => true,
            ],
            [
                'name' => 'Fresh Bakery Supplies',
                'code' => 'SUP-011',
                'contact_name' => 'Piseth Lim',
                'contact_phone' => '+855-12-345-789',
                'email' => 'orders@freshbakery.com.kh',
                'address' => '808 Street 51, Phnom Penh',
                'type' => 'bakery',
                'payment_terms' => 'net_15',
                'notes' => 'Flour, yeast, and baking supplies',
                'is_active' => true,
            ],
            [
                'name' => 'Frozen Foods International',
                'code' => 'SUP-012',
                'contact_name' => 'Makara Heng',
                'contact_phone' => '+855-12-456-890',
                'email' => 'sales@frozenfoods.com.kh',
                'address' => '909 National Road 2, Phnom Penh',
                'type' => 'frozen',
                'payment_terms' => 'net_45',
                'notes' => 'Frozen vegetables, fruits, and seafood',
                'is_active' => true,
            ],
            [
                'name' => 'Tonle Sap Fish Market',
                'code' => 'SUP-013',
                'contact_name' => 'Chantha Mao',
                'contact_phone' => '+855-12-567-901',
                'email' => 'market@tonlesapfish.com',
                'address' => '1010 Riverside, Kampong Chhnang',
                'type' => 'seafood',
                'payment_terms' => 'cod',
                'notes' => 'Fresh river fish - Local catch',
                'is_active' => true,
            ],
            [
                'name' => 'Import Gourmet Foods',
                'code' => 'SUP-014',
                'contact_name' => 'Sopheak Tan',
                'contact_phone' => '+855-12-678-012',
                'email' => 'info@importgourmet.com',
                'address' => '1111 Street 240, Phnom Penh',
                'type' => 'specialty',
                'payment_terms' => 'net_60',
                'notes' => 'Imported specialty ingredients - European & Asian',
                'is_active' => true,
            ],
            [
                'name' => 'Budget Wholesale Foods',
                'code' => 'SUP-015',
                'contact_name' => 'Kosal Vann',
                'contact_phone' => '+855-12-789-123',
                'email' => 'wholesale@budgetfoods.com.kh',
                'address' => '1212 National Road 3, Phnom Penh',
                'type' => 'dry_goods',
                'payment_terms' => 'net_30',
                'notes' => 'Budget-friendly bulk items - Discontinued due to quality issues',
                'is_active' => false,
            ],
        ];

        foreach ($suppliers as $supplier) {
            Supplier::updateOrCreate(
                ['code' => $supplier['code']],
                $supplier
            );
        }
    }
}
